# Power
TARGET_HAS_LEGACY_POWER_STATS := true
TARGET_HAS_NO_WIFI_STATS := true
TARGET_USES_INTERACTION_BOOST := true 

# Power HAL
TARGET_POWERHAL_SET_INTERACTIVE_EXT := device/samsung/msm8226-common/power/power_ext.c
TARGET_POWERHAL_VARIANT := qcom
